= Content

== Conferences

* CodeTalks 2018: D-BAS
* CodeTalks 2019: Clojure
* JavaLand 2020: CfP for Clojure and Stracciatella

== Gettin on stage

* General
** Whats is it about?
** Do I want to listen to the talk?
** Pick curiousity

* Content
** Best practice
** Anti patterns
** Introduction vs expert level
** Overview vs one deteail
** Experience
** Case story (success or failure)

* Write your story / talk
** The more the better
** Variants
** Ask questions
** Get feedback
** Take a break

* Afterwards
** What is your message?
** Why do you want to talk about?
** What story do I want to tell?
** Why is it interesting?

* *The title!*

== Bio


=== Current one

Tobias has more than five years of experience as professional full stack developer. After finishing his academic career with a PhD in dialog-based online argumentation, he decided to join METRONOM in the mid of 2018. Since then, he and his team are continuously improving METRO's customer order fulfillment processes. They provide their colleagues in the stores with first-class digital tools accelerating the management of thousands of articles over several freshness zones. Tobias's daily obsession: minimize and simplify the communication about customers' order information using online services.

In his spare time he loves to write Clojure, and if you don't find him coding, he is standing in front of his barbecue or lifting some dumbbells.


== Code Talks 2019

=== Hitchhiker's Guide to efficient App Development

Did you ever asked yourself how are you able to best serve your customer needs? Should you offer an app? A responsive websites? Should you do cross-platform development, a progressive web app or a native app? There are many patterns and ways to create mobile applications. If you want to have an app on your smartphone, which frameworks or ways are worth to look at, where should you start or is your responsive website already enough? Answers will be given in this talk!
 
In this talk we elaborate different ways of writing apps and provide an overview of state of the art frameworks and techniques. I will share my experience as a former Android developer and provide live coding with Google's Cross-Platform-Framework called Flutter for a small Quiz App.


=== We are all couch potatoes, so let's add SOFAs to our Services

When you code your next service, will you provide a RESTful API, a message queue or something like GraphQL? Did you ask yourself, what are the benefits or drawbacks for you? With which approach will you to code less, but still have a stable interface?
 
In the first part we will compare different approaches for writing APIs. The second part is about one approach called GraphQL, which is a query language for the database of a service. In last part you can lean back and I will provide you a SOFA to a small service. This will then create a RESTful API on top of the current GraphQL server.

* Write your interactive APIs with GraphiQL
* https://sofa-api.com/docs/
* https://solace.com/blog/experience-awesomeness-event-driven-microservices/
* https://medium.com/the-guild/sofa-the-best-way-to-rest-is-graphql-d9da6e8e7693


=== How we almost delivered 100 tons of Stracciatella Mousse

It's not a bug, it's a feature! How often do we read or hear this saying? At what point in time are you confident to say that it's a feature? Is it when your service has a very good test-coverage, a user-focused design and never acts out of line because it utilizes fancy front-end testing tools and canary-releases? Even with seemingly perfect coverage along all levels of the test pyramid, we wonder why bugs appear.
 
This talk is about how we almost delivered 100 tons of Stracciatella Mousse. On time! This was not a bug in production. A store employee confirmed that specific order. Nevertheless this behavior sounds strange enough to investigate. That's why we stepped back. Took a deep breath and had a look at our metrics.

- data-driven company aka monitor your data like if it is your code

* It's not a bug: https://mcc5-metrodr.datadoghq.com/dashboard/6k7-r2d-uxd/oom-turnover-statistics?tile_size=m
* Goal: KPI your Software
* https://leanstartup.co/how-to-turn-data-and-metrics-into-the-right-kind-of-action/
* 99.999 kartons ~ 100t
* https://metro-dr.slack.com/archives/G5C0MQU74/p1558095898011900


=== No Pain, No Gain: Using Clojure for Web Applications

Many of us are really into the paradigms of functional programming. Whether we like streams, mappings, pure functions or just the immutability of variables and objects. But can you use a modern functional programming language like Clojure for web applications? How does it feel when you write HTML with a functional language and which benefits is the backend going to have?

This talk provides a look at a web framework called Component in Clojure, dives into the world of lambda expression, and shows how to develop a WebShop-app with this framework. A live demo and coding will complete our functional lookout.


=== The Good, the Bad and the Ugly Software Architect

No no, our software architect is rather not violent, nor one won't do gunfights in the desert. Nevertheless the architect will shoot people if they choose the wrong architecture for their next software project, so please listen carefully!

Requirements for big software products are constantly changing over time. We had monolithic structured, micro and macro services as well as serveless architectures. There was REST for communication, now we decouple services via message queues etc. Next to that not all architects are aware of proper decision making processes to choose the right approach or sometimes some teams even don't have an architect. That's why this talk should give you some insight into behavioural patterns of a software architect, whereby we will have a look on the good, the bad and the ugly side.